services:
  - type: web
    name: telegram-bot
    env: python
    plan: free
    buildCommand: ""
    startCommand: python main.py
    envVars:
      - key: API_TOKEN
        value: 7541705762:AAEkCpMBSJbakGN1mlgwC2UEui56Rm_w0h0
